#pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 17:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('photo', '0001_initial'), ('photo', '0002_auto_20160321_1607'), ('photo', '0003_developer'), ('photo', '0004_filmroll'), ('photo', '0005_auto_20160321_1636'), ('photo', '0006_auto_20160321_1637'), ('photo', '0007_filmroll_photographer'), ('photo', '0008_auto_20160321_1707'), ('photo', '0009_filmroll_contact_sheet'), ('photo', '0010_photopaper'), ('photo', '0011_auto_20160321_1811'), ('photo', '0012_auto_20160321_1818'), ('photo', '0013_auto_20160321_1821'), ('photo', '0014_film_process'), ('photo', '0015_auto_20160321_1927'), ('photo', '0016_auto_20160321_1939'), ('photo', '0017_auto_20160324_1622')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll_film', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('speed', models.IntegerField()),
                ('formats', models.ManyToManyField(to='photo.FilmFormat')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Manufacturer'),
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('powder', models.BooleanField()),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='FilmRoll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('shot_speed', models.PositiveIntegerField()),
                ('developed_speed', models.PositiveIntegerField()),
                ('shot_date', models.DateField(blank=True, null=True)),
                ('developed_date', models.DateField(blank=True, null=True)),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photo.Developer')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Film')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.FilmFormat')),
                ('photographer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('contact_sheet', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('paper_type', models.CharField(choices=[('RC', 'resin-coated'), ('FB', 'fibre-based')], max_length=2)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Manufacturer')),
                ('grade', models.IntegerField(blank=True, choices=[(-1, '00'), (0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('multigrade', models.BooleanField(default=True)),
                ('finishes', models.ManyToManyField(to='photo.PhotoPaperFinishes')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoPaperFinish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='process',
            field=models.CharField(choices=[('B&W', 'black and white'), ('C41', 'C-41'), ('E6', 'E-6')], max_length=3),
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ('manufacturer__short_name', 'name')},
        ),
    ]
