# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 17:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('powder', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('speed', models.IntegerField()),
                ('process', models.CharField(choices=[('B&W', 'black and white'), ('C41', 'C-41'), ('E6', 'E-6')], max_length=3)),
            ],
            options={
                'ordering': ('manufacturer__short_name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='FilmFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll_film', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FilmRoll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('shot_speed', models.PositiveIntegerField()),
                ('developed_speed', models.PositiveIntegerField()),
                ('shot_date', models.DateField(blank=True, null=True)),
                ('developed_date', models.DateField(blank=True, null=True)),
                ('contact_sheet', models.ImageField(blank=True, upload_to='')),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photo.Developer')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Film')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.FilmFormat')),
                ('photographer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('paper_type', models.CharField(choices=[('RC', 'resin-coated'), ('FB', 'fibre-based')], max_length=2)),
                ('multigrade', models.BooleanField()),
                ('grade', models.IntegerField(blank=True, choices=[(-1, '00'), (0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoPaperFinish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='photopaper',
            name='finishes',
            field=models.ManyToManyField(to='photo.PhotoPaperFinish'),
        ),
        migrations.AddField(
            model_name='photopaper',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Manufacturer'),
        ),
        migrations.AddField(
            model_name='film',
            name='formats',
            field=models.ManyToManyField(to='photo.FilmFormat'),
        ),
        migrations.AddField(
            model_name='film',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Manufacturer'),
        ),
        migrations.AddField(
            model_name='developer',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Manufacturer'),
        ),
    ]
