#pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import photo.utils


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmroll',
            name='contact_sheet',
            field=models.ImageField(blank=True, upload_to=photo.utils.UploadToPathAndRename('contacts')),
        ),
    ]
