#pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import photo.utils
import uuid


class Migration(migrations.Migration):

    replaces = [('photo', '0003_negative'), ('photo', '0004_auto_20160324_1839')]

    dependencies = [
        ('photo', '0002_auto_20160324_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Negative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('film_roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.FilmRoll')),
                ('index', models.CharField(default=0, max_length=10)),
                ('scan', models.ImageField(blank=True, upload_to=photo.utils.UploadToPathAndRename('negatives'))),
            ],
        ),
    ]
