#pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_developer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmRoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('shot_speed', models.PositiveIntegerField()),
                ('developed_speed', models.PositiveIntegerField()),
                ('shot_date', models.DateField(blank=True)),
                ('developed_date', models.DateField(blank=True)),
                ('developer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='photo.Developer')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Film')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.FilmFormat')),
            ],
        ),
    ]
