#pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_negative_squashed_0004_auto_20160324_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmroll',
            name='developed_speed',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='filmroll',
            name='shot_speed',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='negative',
            name='index',
            field=models.CharField(max_length=10),
        ),
    ]
