#pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20160324_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='negative',
            options={'ordering': ('film_roll__name', 'index')},
        ),
    ]
