#pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_filmroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmroll',
            name='developed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filmroll',
            name='shot_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
