#pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_auto_20160324_1927'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Negative',
            new_name='Frame',
        ),
    ]
