#pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_auto_20160324_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='index',
            field=models.SmallIntegerField(),
        ),
    ]
