# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 17:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photo', '0006_auto_20160321_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmroll',
            name='photographer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
