#pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 17:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_filmroll_photographer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmroll',
            name='photographer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
