#pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import photo.utils


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_auto_20160324_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='scan',
            field=models.ImageField(blank=True, upload_to=photo.utils.UploadToPathAndRename('frames')),
        ),
    ]
