# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0008_auto_20160321_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmroll',
            name='contact_sheet',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
