#pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import photo.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0008_auto_20160325_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Print',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('sequence', models.SmallIntegerField()),
                ('scan', models.ImageField(blank=True, upload_to=photo.utils.UploadToPathAndRename('prints'))),
                ('finish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.PhotoPaperFinish')),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Frame')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.PhotoPaper')),
            ],
            options={
                'ordering': ('date', 'sequence'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='print',
            unique_together=set([('date', 'sequence')]),
        ),
    ]
