#pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0009_filmroll_contact_sheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('paper_type', models.CharField(choices=[('RC', 'resin-coated'), ('FB', 'fibre-based')], max_length=2)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Manufacturer')),
            ],
        ),
    ]
