#pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0010_photopaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='photopaper',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(-1, '00'), (0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='photopaper',
            name='multigrade',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
