#pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0012_auto_20160321_1818'),
    ]

    operations = [
        migrations.RenameModel('PhotoPaperFinishes', 'PhotoPaperFinish')
    ]
