#pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0014_film_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='process',
            field=models.CharField(choices=[('B&W', 'black and white'), ('C41', 'C-41'), ('E6', 'E-6')], max_length=3),
        ),
    ]
