# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0015_auto_20160321_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ('manufacturer__short_name', 'name')},
        ),
    ]
